INSERT INTO Guest (guestName) VALUES ('Inga Ishikawa');
INSERT INTO Guest (guestName) VALUES ('Brandy Barkman');
INSERT INTO Guest (guestName) VALUES ('Asley Agin');
INSERT INTO Guest (guestName) VALUES ('Tomeka Thrasher');
INSERT INTO Guest (guestName) VALUES ('Venita Vong');
INSERT INTO Guest (guestName) VALUES ('Yong Yoon');
INSERT INTO Guest (guestName) VALUES ('Myong Montenegro');
INSERT INTO Guest (guestName) VALUES ('Kerri Kretschmer');
INSERT INTO Guest (guestName) VALUES ('Cordia Carico');
INSERT INTO Guest (guestName) VALUES ('Lakeesha Litke');
INSERT INTO Guest (guestName) VALUES ('Kevin Krehbiel');
INSERT INTO Guest (guestName) VALUES ('Roma Rhynes');
INSERT INTO Guest (guestName) VALUES ('Ryann Randall');
INSERT INTO Guest (guestName) VALUES ('Gaston Grogg');
INSERT INTO Guest (guestName) VALUES ('Sheldon Stelzer');
INSERT INTO Guest (guestName) VALUES ('Thuy Townes');
INSERT INTO Guest (guestName) VALUES ('Gwendolyn Gladney');
INSERT INTO Guest (guestName) VALUES ('Kristopher Kyler');
INSERT INTO Guest (guestName) VALUES ('Gonzalo Guffey');
INSERT INTO Guest (guestName) VALUES ('Paz Piro');
INSERT INTO Guest (guestName) VALUES ('Tommie Toribio');
INSERT INTO Guest (guestName) VALUES ('Grady Guse');
INSERT INTO Guest (guestName) VALUES ('Jamee Jerrell');
INSERT INTO Guest (guestName) VALUES ('Eda Eagan');
INSERT INTO Guest (guestName) VALUES ('Ronny Rodarte');
INSERT INTO Guest (guestName) VALUES ('Katie Kellar');
INSERT INTO Guest (guestName) VALUES ('Delcie Darst');
INSERT INTO Guest (guestName) VALUES ('Mellisa Moles');
INSERT INTO Guest (guestName) VALUES ('Retta Rago');
INSERT INTO Guest (guestName) VALUES ('Natalie Nicholls');
INSERT INTO Guest (guestName) VALUES ('Brenton Brandenburg');
INSERT INTO Guest (guestName) VALUES ('Lashaun Landi');
INSERT INTO Guest (guestName) VALUES ('Becki Badalamenti');
INSERT INTO Guest (guestName) VALUES ('Denis Dedeaux');
INSERT INTO Guest (guestName) VALUES ('Roderick Rodriguz');
INSERT INTO Guest (guestName) VALUES ('Verline Venturi');
INSERT INTO Guest (guestName) VALUES ('Vina Vanetten');
INSERT INTO Guest (guestName) VALUES ('Chia Constance');
INSERT INTO Guest (guestName) VALUES ('Sandee Sosnowski');
INSERT INTO Guest (guestName) VALUES ('Kerry Kleve');
INSERT INTO Guest (guestName) VALUES ('Darell Dirks');
INSERT INTO Guest (guestName) VALUES ('Leann Lauer');
INSERT INTO Guest (guestName) VALUES ('Wiley Wittrock');
INSERT INTO Guest (guestName) VALUES ('Missy Mancil');
INSERT INTO Guest (guestName) VALUES ('Paige Pfeifer');
INSERT INTO Guest (guestName) VALUES ('Veronika Vowels');
INSERT INTO Guest (guestName) VALUES ('Kathi Kuhlman');
INSERT INTO Guest (guestName) VALUES ('Aleisha Atchley');
INSERT INTO Guest (guestName) VALUES ('Wilma Wedeking');
INSERT INTO Guest (guestName) VALUES ('Nellie Nolley');
INSERT INTO Drivers (driverName) VALUES ('Nicole Howard');
INSERT INTO Drivers (driverName) VALUES ('Ferdinand Berger');
INSERT INTO Drivers (driverName) VALUES ('Myrna Pace');
INSERT INTO Drivers (driverName) VALUES ('Mallory Hudson');
INSERT INTO Drivers (driverName) VALUES ('Dallas Gilbert');
INSERT INTO Drivers (driverName) VALUES ('Catherine West');
INSERT INTO Drivers (driverName) VALUES ('Georgette Atkins');
INSERT INTO Drivers (driverName) VALUES ('Leanne Le');
INSERT INTO Drivers (driverName) VALUES ('Jesus Mcintosh');
INSERT INTO Drivers (driverName) VALUES ('Hiram Flowers');
INSERT INTO Trip (direction, driverId, carId, timeStart, timeArrival) VALUES ('Hotel->Airport', 1, 2, '11:30', '11:52');
INSERT INTO Trip (direction, driverId, carId, timeStart, timeArrival) VALUES ('Airport->Hotel', 1, 2, '12:04', '12:26');
INSERT INTO Trip (direction, driverId, carId, timeStart, timeArrival) VALUES ('Hotel->Airport', 2, 1, '13:30', '13:51');
INSERT INTO Trip (direction, driverId, carId, timeStart, timeArrival) VALUES ('Airport->Hotel', 2, 1, '13:58', '14:20');
INSERT INTO Cars (carName, carPassengers) VALUES ('Monster Truck: Crocodile Alpha', 1);
INSERT INTO Cars (carName, carPassengers) VALUES ('Monster Truck: Ocelot Prime', 1);
INSERT INTO Cars (carName, carPassengers) VALUES ('Micra Mouse', 2);
INSERT INTO Cars (carName, carPassengers) VALUES ('Van', 5);
