INSERT INTO guest (guestName) VALUES ('Inga Ishikawa');
INSERT INTO guest (guestName) VALUES ('Brandy Barkman');
INSERT INTO guest (guestName) VALUES ('Asley Agin');
INSERT INTO guest (guestName) VALUES ('Tomeka Thrasher');
INSERT INTO guest (guestName) VALUES ('Venita Vong');
INSERT INTO guest (guestName) VALUES ('Yong Yoon');
INSERT INTO guest (guestName) VALUES ('Myong Montenegro');
INSERT INTO guest (guestName) VALUES ('Kerri Kretschmer');
INSERT INTO guest (guestName) VALUES ('Cordia Carico');
INSERT INTO guest (guestName) VALUES ('Lakeesha Litke');
INSERT INTO guest (guestName) VALUES ('Kevin Krehbiel');
INSERT INTO guest (guestName) VALUES ('Roma Rhynes');
INSERT INTO guest (guestName) VALUES ('Ryann Randall');
INSERT INTO guest (guestName) VALUES ('Gaston Grogg');
INSERT INTO guest (guestName) VALUES ('Sheldon Stelzer');
INSERT INTO guest (guestName) VALUES ('Thuy Townes');
INSERT INTO guest (guestName) VALUES ('Gwendolyn Gladney');
INSERT INTO guest (guestName) VALUES ('Kristopher Kyler');
INSERT INTO guest (guestName) VALUES ('Gonzalo Guffey');
INSERT INTO guest (guestName) VALUES ('Paz Piro');
INSERT INTO guest (guestName) VALUES ('Tommie Toribio');
INSERT INTO guest (guestName) VALUES ('Grady Guse');
INSERT INTO guest (guestName) VALUES ('Jamee Jerrell');
INSERT INTO guest (guestName) VALUES ('Eda Eagan');
INSERT INTO guest (guestName) VALUES ('Ronny Rodarte');
INSERT INTO guest (guestName) VALUES ('Katie Kellar');
INSERT INTO guest (guestName) VALUES ('Delcie Darst');
INSERT INTO guest (guestName) VALUES ('Mellisa Moles');
INSERT INTO guest (guestName) VALUES ('Retta Rago');
INSERT INTO guest (guestName) VALUES ('Natalie Nicholls');
INSERT INTO guest (guestName) VALUES ('Brenton Brandenburg');
INSERT INTO guest (guestName) VALUES ('Lashaun Landi');
INSERT INTO guest (guestName) VALUES ('Becki Badalamenti');
INSERT INTO guest (guestName) VALUES ('Denis Dedeaux');
INSERT INTO guest (guestName) VALUES ('Roderick Rodriguz');
INSERT INTO guest (guestName) VALUES ('Verline Venturi');
INSERT INTO guest (guestName) VALUES ('Vina Vanetten');
INSERT INTO guest (guestName) VALUES ('Chia Constance');
INSERT INTO guest (guestName) VALUES ('Sandee Sosnowski');
INSERT INTO guest (guestName) VALUES ('Kerry Kleve');
INSERT INTO guest (guestName) VALUES ('Darell Dirks');
INSERT INTO guest (guestName) VALUES ('Leann Lauer');
INSERT INTO guest (guestName) VALUES ('Wiley Wittrock');
INSERT INTO guest (guestName) VALUES ('Missy Mancil');
INSERT INTO guest (guestName) VALUES ('Paige Pfeifer');
INSERT INTO guest (guestName) VALUES ('Veronika Vowels');
INSERT INTO guest (guestName) VALUES ('Kathi Kuhlman');
INSERT INTO guest (guestName) VALUES ('Aleisha Atchley');
INSERT INTO guest (guestName) VALUES ('Wilma Wedeking');
INSERT INTO guest (guestName) VALUES ('Nellie Nolley');
INSERT INTO drivers (driverName) VALUES ('Nicole Howard');
INSERT INTO drivers (driverName) VALUES ('Ferdinand Berger');
INSERT INTO drivers (driverName) VALUES ('Myrna Pace');
INSERT INTO drivers (driverName) VALUES ('Mallory Hudson');
INSERT INTO drivers (driverName) VALUES ('Dallas Gilbert');
INSERT INTO drivers (driverName) VALUES ('Catherine West');
INSERT INTO drivers (driverName) VALUES ('Georgette Atkins');
INSERT INTO drivers (driverName) VALUES ('Leanne Le');
INSERT INTO drivers (driverName) VALUES ('Jesus Mcintosh');
INSERT INTO drivers (driverName) VALUES ('Hiram Flowers');
INSERT INTO cars (carName, carPassengers) VALUES ('Monster Truck: Crocodile Alpha', 1);
INSERT INTO cars (carName, carPassengers) VALUES ('Monster Truck: Ocelot Prime', 1);
INSERT INTO cars (carName, carPassengers) VALUES ('Micra Mouse', 2);
INSERT INTO cars (carName, carPassengers) VALUES ('Van', 5);
INSERT INTO cars (carName, carPassengers) VALUES ('Limousine', 5);
INSERT INTO trip (direction, driverId, carId, tripdate, timeStart, timeArrival)
        VALUES ('Hotel->Airport', 1, 2, date('2020-02-15'), '11:30', '11:52');
INSERT INTO trip (direction, driverId, carId, tripdate, timeStart, timeArrival)
        VALUES ('Airport->Hotel', 1, 2, date('2020-02-15'), '12:04', '12:26');
INSERT INTO trip (direction, driverId, carId, tripdate, timeStart, timeArrival)
        VALUES ('Hotel->Airport', 9, 4, date('2020-02-17'), '13:30', '13:51');
INSERT INTO trip (direction, driverId, carId, tripdate, timeStart, timeArrival)
        VALUES ('Airport->Hotel', 10, 5, date('2020-02-17'), '13:58', '14:20');

UPDATE main.guest SET pickuptrip = 1, dropofftrip = 2 WHERE guestid = 1;
UPDATE main.guest SET pickuptrip = 1, dropofftrip = 4 WHERE guestid = 1;
UPDATE main.guest SET pickuptrip = 3, dropofftrip = 4 WHERE guestid = 1;
UPDATE main.guest SET pickuptrip = 3, dropofftrip = 4 WHERE guestid = 1;
UPDATE main.guest SET pickuptrip = 3, dropofftrip = 4 WHERE guestid = 1;
UPDATE main.guest SET pickuptrip = 3, dropofftrip = 4 WHERE guestid = 1;
UPDATE main.guest SET pickuptrip = 1, dropofftrip = 4 WHERE guestid = 1;
